version: '3.3'

services:
  mongo_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:${MONGO_DB_DIR}
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    #build: ./ui  
    image: ${DOCKERHUB_USERNAME}/ui:${IMG_VERSION}
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${PUMA_PORT}:${PUMA_PORT}/tcp
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_net

  # post:
  #   #build: ./post-py
  #   image: ${DOCKERHUB_USERNAME}/post:${IMG_VERSION}
  #   networks:
  #     - back_net
  #     - front_net

  post:
    image: ${DOCKERHUB_USERNAME}/post:${IMG_VERSION}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    # depends_on:
    #   - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - back_net
      - front_net


  comment:
    #build: ./comment
    image: ${DOCKERHUB_USERNAME}/comment:${IMG_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.2.0/24"
  front_net:
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/24"
  